export const FAKE_POPULARS = [
  {
    backdrop_path: '/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg',
    first_air_date: '2022-11-23',
    genre_ids: [10765, 9648, 35],
    id: 119051,
    name: 'Wednesday',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Wednesday',
    overview:
      'Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.',
    popularity: 5797.458,
    poster_path: '/9PFonBhy4cQy7Jz20NpMygczOkv.jpg',
    vote_average: 9.999,
    vote_count: 2827,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: '/s1xnjbOIQtwGObPnydTebp74G2c.jpg',
    id: 90669,
    name: '1899',
    original_language: 'de',
    original_name: '1899',
    overview:
      'Passengers on an immigrant ship traveling to the new continent get caught in a mysterious riddle when they find a second vessel adrift on the open sea.',
    poster_path: '/gZleGu1MQVBArH2dlpZ9CGi0hhy.jpg',
    media_type: 'tv',
    genre_ids: [9648, 18],
    popularity: 655.432,
    first_air_date: '2022-11-17',
    vote_average: 7.905,
    vote_count: 531,
    origin_country: ['DE'],
  },
  {
    adult: false,
    backdrop_path: '/hIZFG7MK4leU4axRFKJWqrjhmxZ.jpg',
    id: 95403,
    name: 'The Peripheral',
    original_language: 'en',
    original_name: 'The Peripheral',
    overview:
      'Stuck in a small Appalachian town, a young woman’s only escape from the daily grind is playing advanced video games. She is such a good player that a company sends her a new video game system to test…but it has a surprise in store. It unlocks all of her dreams of finding a purpose, romance, and glamour in what seems like a game…but it also puts her and her family in real danger.',
    poster_path: '/ccBe5BVeibdBEQU7l6P6BubajWV.jpg',
    media_type: 'tv',
    genre_ids: [10765, 18],
    popularity: 538.158,
    first_air_date: '2022-10-20',
    vote_average: 8.074,
    vote_count: 414,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg',
    id: 94997,
    name: 'House of the Dragon',
    original_language: 'en',
    original_name: 'House of the Dragon',
    overview:
      'The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.',
    poster_path: '/z2yahl2uefxDCl0nogcRBstwruJ.jpg',
    media_type: 'tv',
    genre_ids: [10765, 18, 10759],
    popularity: 575.483,
    first_air_date: '2022-08-21',
    vote_average: 8.493,
    vote_count: 2586,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/93SxdkiR3gBcbG5FxIt0DCBttul.jpg',
    id: 111837,
    name: 'Willow',
    original_language: 'en',
    original_name: 'Willow',
    overview:
      'Many years after the events of the original film, legendary sorcerer Willow leads a group of misfit heroes on a dangerous rescue mission through a world beyond their wildest imaginations.',
    poster_path: '/jhdSPDlhswjN1r6O0pGP3ZvQgU8.jpg',
    media_type: 'tv',
    genre_ids: [10765, 10759, 18],
    popularity: 1672.206,
    first_air_date: '2022-11-30',
    vote_average: 6.2,
    vote_count: 61,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
    id: 66732,
    name: 'Stranger Things',
    original_language: 'en',
    original_name: 'Stranger Things',
    overview:
      'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
    poster_path: '/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    media_type: 'tv',
    genre_ids: [18, 10765, 9648],
    popularity: 282.122,
    first_air_date: '2016-07-15',
    vote_average: 8.6,
    vote_count: 14545,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/cSqUkhWH5seTIwtqUUAEBFjiLyh.jpg',
    id: 93405,
    name: 'Squid Game',
    original_language: 'ko',
    original_name: '오징어 게임',
    overview:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games—with high stakes. But, a tempting prize awaits the victor.",
    poster_path: '/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
    media_type: 'tv',
    genre_ids: [10759, 9648, 18],
    popularity: 140.746,
    first_air_date: '2021-09-17',
    vote_average: 7.837,
    vote_count: 11990,
    origin_country: ['KR'],
  },
  {
    adult: false,
    backdrop_path: '/y3Y5INbgpttPTbgihgIa5mdUJqH.jpg',
    id: 113988,
    name: 'Dahmer – Monster: The Jeffrey Dahmer Story',
    original_language: 'en',
    original_name: 'Dahmer – Monster: The Jeffrey Dahmer Story',
    overview:
      'This series examines the gruesome and horrific true crimes of Jeffrey Dahmer and the systemic failures that enabled one of America’s most notorious serial killers to continue his murderous spree in plain sight for over a decade.',
    poster_path: '/f2PVrphK0u81ES256lw3oAZuF3x.jpg',
    media_type: 'tv',
    genre_ids: [80, 18],
    popularity: 365.815,
    first_air_date: '2022-09-21',
    vote_average: 8.147,
    vote_count: 1716,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/8V1XPEDLtJoxOWlE6gYzn2sQaMp.jpg',
    id: 60574,
    name: 'Peaky Blinders',
    original_language: 'en',
    original_name: 'Peaky Blinders',
    overview:
      'A gangster family epic set in 1919 Birmingham, England and centered on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby, who means to move up in the world.',
    poster_path: '/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg',
    media_type: 'tv',
    genre_ids: [18, 80],
    popularity: 379.029,
    first_air_date: '2013-09-12',
    vote_average: 8.553,
    vote_count: 7877,
    origin_country: ['GB'],
  },
  {
    adult: false,
    backdrop_path: '/1rO4xoCo4Z5WubK0OwdVll3DPYo.jpg',
    id: 84773,
    name: 'The Lord of the Rings: The Rings of Power',
    original_language: 'en',
    original_name: 'The Lord of the Rings: The Rings of Power',
    overview:
      'Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.',
    poster_path: '/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg',
    media_type: 'tv',
    genre_ids: [10765, 10759, 18],
    popularity: 472.878,
    first_air_date: '2022-09-01',
    vote_average: 7.548,
    vote_count: 1641,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg',
    id: 94605,
    name: 'Arcane',
    original_language: 'en',
    original_name: 'Arcane',
    overview:
      'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
    poster_path: '/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg',
    media_type: 'tv',
    genre_ids: [16, 10765, 10759, 18],
    popularity: 68.055,
    first_air_date: '2021-11-06',
    vote_average: 8.746,
    vote_count: 2737,
    origin_country: ['US'],
  },
];
